### ISSUE TITLE
AttributeError: 'Function' object has no attribute 'get_marker'

### ISSUE THREAD

**Issue by rossmacarthur** [pytest-dev/pytest-cov#252]
I just started getting the following error with pytest-cov v2.6.0, pytest v4.1.0 on Python 3.4.6, PyPy, and PyPy3

```
self = <pytest_cov.plugin.CovPlugin object at 0x110f365c0>, item = <Function test_x>

    @compat.hookwrapper
    def pytest_runtest_call(self, item):
>       if (item.get_marker('no_cover')
                or 'no_cover' in getattr(item, 'fixturenames', ())):
E               AttributeError: 'Function' object has no attribute 'get_marker'

../.pyenv/versions/3.4.9/envs/venv/lib/python3.4/site-packages/pytest_cov/plugin.py:289: AttributeError
```

## How to replicate

- Create a virtualenv with Python 3.4.9
- `pip install pytest==4.1.0 pytest-cov==2.6.0`

- Create `something.py` with the following contents:

```python
def test_x():
    assert True
```

- Run `pytest --cov=something something.py`

## Pytest output

```
========================================================== test session starts ===========================================================
platform darwin -- Python 3.4.9, pytest-4.1.0, py-1.7.0, pluggy-0.8.0 -- /Users/ross/.pyenv/versions/3.4.9/envs/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/ross/temp, inifile:
plugins: cov-2.6.0
collected 1 item

something.py::test_x FAILED                                                                                                        [100%]

================================================================ FAILURES ================================================================
_________________________________________________________________ test_x _________________________________________________________________

self = <pytest_cov.plugin.CovPlugin object at 0x110f365c0>, item = <Function test_x>

    @compat.hookwrapper
    def pytest_runtest_call(self, item):
>       if (item.get_marker('no_cover')
                or 'no_cover' in getattr(item, 'fixturenames', ())):
E               AttributeError: 'Function' object has no attribute 'get_marker'

../.pyenv/versions/3.4.9/envs/venv/lib/python3.4/site-packages/pytest_cov/plugin.py:289: AttributeError

---------- coverage: platform darwin, python 3.4.9-final-0 -----------
Name           Stmts   Miss  Cover
----------------------------------
something.py       2      1    50%

======================================================== 1 failed in 0.07 seconds ========================================================
```

**Comment by rossmacarthur** [comment]
Possibly because of one of these?
https://github.com/pytest-dev/pytest/pull/4564
https://github.com/pytest-dev/pytest/pull/3978

**Comment by bbernays** [comment]
We are seeing the same error with latest version of ```pytest```.

OK: ```pytest==4.02``` with ```pytest-cov-2.6.0```
FAILS: ```pytest==4.1.0``` with ```pytest-cov-2.6.0```

**Comment by blueyed** [comment]
Fixed in https://github.com/pytest-dev/pytest-cov/pull/253.

**Comment by blueyed** [comment]
pytest-cov is not tested against current/newer pytest versions.
It is being worked on in https://github.com/pytest-dev/pytest-cov/pull/240.

**Comment by nicoddemus** [comment]
> this should have been triggering errors since pytest==4.0.0

Indeed, that was the idea... can anyone explain why was that not the case? Perhaps migrating directly from 3.X to 4.1 caused this?

**Comment by ionelmc** [comment]
pytest-cov 2.6.1 is released.

**Comment by AlmogCohen** [comment]
It still happens on `2.6.1` for all python versions I could check, not sure if it was meant to solve that...

```

item = <Function test_execute_traffic_simulation_query__with_target>

    def pytest_runtest_teardown(item):
>       if not item.get_marker('withoutresponses'):
E       AttributeError: 'Function' object has no attribute 'get_marker'

../../../../.local/share/virtualenvs/algosec-ePKRVxQ0/lib/python2.7/site-packages/pytest_responses.py:13: AttributeError
======================================================================================= 196 error in 0.94 seconds ========================================================================================
(algosec-ePKRVxQ0) ➜  algosec git:(fix-travis) ✗ pytest --version
This is pytest version 4.1.1, imported from /Users/almogcohen/.local/share/virtualenvs/algosec-ePKRVxQ0/lib/python2.7/site-packages/pytest.pyc
setuptools registered plugins:
  pytest-responses-0.3.0 at /Users/almogcohen/.local/share/virtualenvs/algosec-ePKRVxQ0/lib/python2.7/site-packages/pytest_responses.py
  pytest-mock-1.10.0 at /Users/almogcohen/.local/share/virtualenvs/algosec-ePKRVxQ0/lib/python2.7/site-packages/pytest_mock.py
  pytest-cov-2.6.1 at /Users/almogcohen/.local/share/virtualenvs/algosec-ePKRVxQ0/lib/python2.7/site-packages/pytest_cov/plugin.py
(algosec-ePKRVxQ0) ➜  algosec git:(fix-travis) ✗
```

You can see the travis run from an hour ago that fails for all versions https://travis-ci.org/algosec/algosec-python/jobs/480653324

Any suggestions for a fix?

**Comment by AlmogCohen** [comment]
Could you please link to the PR where you fixed this issue so I can fix it in another repo depending on pytest?

**Comment by rossmacarthur** [comment]
@AlmogCohen I do believe it was fixed in https://github.com/pytest-dev/pytest-cov/pull/253

**Comment by The-Compiler** [comment]
@AlmogCohen Note there is https://github.com/getsentry/pytest-responses/pull/7 already :wink:

**Comment by rawrgulmuffins** [comment]
Currently seeing this with pytest-cov 2.6.1

```
$ pip list | grep pytest
pytest                             4.2.0
pytest-arraydiff                   0.2
pytest-astropy                     0.3.0
pytest-cov                         2.6.1
pytest-doctestplus                 0.1.3
pytest-openfiles                   0.3.0
pytest-remotedata                  0.2.1
$ python -m pytest
=============================== test session starts ================================
platform darwin -- Python 3.6.5, pytest-4.2.0, py-1.5.3, pluggy-0.8.1
rootdir: /Users/alexl/git/example, inifile: setup.cfg
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, cov-2.6.1, arraydiff-0.2
collected 1 item

tests/test_example.py E                                                      [100%]

====================================== ERRORS ======================================
__________________ ERROR at setup of test_command_line_interface ___________________

item = <Function test_command_line_interface>

    def pytest_runtest_setup(item):

>       remote_data = item.get_marker('remote_data')
E       AttributeError: 'Function' object has no attribute 'get_marker'

/usr/local/anaconda3/lib/python3.6/site-packages/pytest_remotedata/plugin.py:59: AttributeError
============================= 1 error in 0.12 seconds ==============================
```

**Comment by rossmacarthur** [comment]
@rawrgulmuffins This looks like a bug in pytest-remotedata

**Comment by rawrgulmuffins** [comment]
@rossmacarthur I'll go make an issue that links to this one then.

**Comment by BaranOrnarli** [comment]
`conda install pytest`; `pip install pytest-remotedata>=0.3.1` and things start working.

**Comment by endrebak** [comment]
`pip install "pytest-remotedata>=0.3.1"` unless you want to redirect to a file (in fish at least). But otherwise, great fix Baran.

**Comment by prashant-bansod** [comment]
```
======================================= ERRORS =======================================
_________________________ ERROR at setup of test_constructor _________________________

item = <Function test_constructor>

    @hookimpl(tryfirst=True)
    def pytest_runtest_setup(item):
        """
        pytest hook to setup test before run.
        """
>       test_id_marker = item.get_marker('test_id')
E       AttributeError: 'Function' object has no attribute 'get_marker'

/anaconda3/envs/vaak/lib/python3.6/site-packages/topology/pytest/plugin.py:311: AttributeError
============================== 1 error in 0.04 seconds ===============================

```

```
$ pip list | grep pytest

pytest              5.0.1      
pytest-remotedata   0.3.1      
```
Is there any fix for this?  Thanks.

**Comment by The-Compiler** [comment]
@prashant-bansod This seems completely unrelated to pytest-cov or pytest-remotedata. You'll need to ask the author of `topology/pytest/plugin.py` to update their code.

**Comment by nicoddemus** [comment]
Seems to be fixed in `master` already:

https://github.com/astropy/pytest-remotedata/blob/0eef4734770e3003d5b35b65f8c70d8cbeb475ff/pytest_remotedata/plugin.py#L65-L70

**Comment by The-Compiler** [comment]
@nicoddemus It's also fixed in pytest-remotedata 0.3.1 which @prashant-bansod has installed - based on the stacktrace above, the error @prashant-bansod is seeing is in their testsuite (or whatever `topology.pytest.plugin` is).
